#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_ROOT="${FASTPLS_IMAGENET_CLASS_BIAS_RUN_ROOT:-$ROOT_DIR/benchmark_results/imagenet_class_bias_full_$(date +%Y%m%d_%H%M%S)}"
mkdir -p "$RUN_ROOT/logs"

TRAIN_N="${FASTPLS_IMAGENET_TRAIN_N:-1000000}"
TEST_N="${FASTPLS_IMAGENET_TEST_N:-rest}"
NCOMP="${FASTPLS_IMAGENET_NCOMP:-300,500,750,1000}"
METHODS="${FASTPLS_IMAGENET_METHODS:-plssvd,simpls}"
BACKENDS="${FASTPLS_IMAGENET_BACKENDS:-cuda}"
SCALING="${FASTPLS_IMAGENET_SCALING:-centering,none}"
LAMBDA="${FASTPLS_CLASS_BIAS_LAMBDA:-0,0.003,0.005,0.006,0.0075,0.01,0.0125,0.015}"
ITER="${FASTPLS_CLASS_BIAS_ITER:-1,2,3}"
CLIP="${FASTPLS_CLASS_BIAS_CLIP:-Inf,0.25,0.5}"
EPS="${FASTPLS_CLASS_BIAS_EPS:-0.5,1,2}"
CLASSIFIERS="${FASTPLS_IMAGENET_CLASSIFIERS:-argmax,class_bias}"
TOP="${FASTPLS_IMAGENET_TOP:-5}"
SEED="${FASTPLS_IMAGENET_SEED:-123}"
MAX_RUNS="${FASTPLS_IMAGENET_MAX_RUNS:-0}"
MATRIX_CACHE_DIR="${FASTPLS_IMAGENET_MATRIX_CACHE_DIR:-$RUN_ROOT/matrix_cache}"
PREPARE_CACHE_FIRST="${FASTPLS_IMAGENET_PREPARE_CACHE_FIRST:-true}"
GAUSSIAN_Y="${FASTPLS_IMAGENET_GAUSSIAN_Y:-false}"
GAUSSIAN_Y_DIM="${FASTPLS_IMAGENET_GAUSSIAN_Y_DIM:-ncomp}"

OUT_DIR="$RUN_ROOT/results"
LOG_FILE="$RUN_ROOT/logs/benchmark.log"

cat > "$RUN_ROOT/run_parameters.env" <<EOF
RUN_ROOT=$RUN_ROOT
OUT_DIR=$OUT_DIR
LOG_FILE=$LOG_FILE
FASTPLS_IMAGENET_TRAIN_N=$TRAIN_N
FASTPLS_IMAGENET_TEST_N=$TEST_N
FASTPLS_IMAGENET_NCOMP=$NCOMP
FASTPLS_IMAGENET_METHODS=$METHODS
FASTPLS_IMAGENET_BACKENDS=$BACKENDS
FASTPLS_IMAGENET_SCALING=$SCALING
FASTPLS_CLASS_BIAS_LAMBDA=$LAMBDA
FASTPLS_CLASS_BIAS_ITER=$ITER
FASTPLS_CLASS_BIAS_CLIP=$CLIP
FASTPLS_CLASS_BIAS_EPS=$EPS
FASTPLS_IMAGENET_CLASSIFIERS=$CLASSIFIERS
FASTPLS_IMAGENET_TOP=$TOP
FASTPLS_IMAGENET_SEED=$SEED
FASTPLS_IMAGENET_MAX_RUNS=$MAX_RUNS
FASTPLS_IMAGENET_MATRIX_CACHE_DIR=$MATRIX_CACHE_DIR
FASTPLS_IMAGENET_PREPARE_CACHE_FIRST=$PREPARE_CACHE_FIRST
FASTPLS_IMAGENET_GAUSSIAN_Y=$GAUSSIAN_Y
FASTPLS_IMAGENET_GAUSSIAN_Y_DIM=$GAUSSIAN_Y_DIM
EOF

COMMON_ARGS=(
  --out-dir="$OUT_DIR" \
  --train-n="$TRAIN_N" \
  --test-n="$TEST_N" \
  --ncomp="$NCOMP" \
  --methods="$METHODS" \
  --backends="$BACKENDS" \
  --scaling="$SCALING" \
  --lambda="$LAMBDA" \
  --iter="$ITER" \
  --clip="$CLIP" \
  --eps="$EPS" \
  --classifiers="$CLASSIFIERS" \
  --top="$TOP" \
  --seed="$SEED" \
  --max-runs="$MAX_RUNS" \
  --matrix-cache-dir="$MATRIX_CACHE_DIR"
  --gaussian-y="$GAUSSIAN_Y" \
  --gaussian-y-dim="$GAUSSIAN_Y_DIM"
)

: > "$LOG_FILE"
if [[ "${PREPARE_CACHE_FIRST,,}" =~ ^(1|true|yes|y)$ ]]; then
  Rscript benchmark/benchmark_imagenet_class_bias_full_grid.R \
    "${COMMON_ARGS[@]}" \
    --prepare-cache-only=true \
    2>&1 | tee -a "$LOG_FILE"
fi

Rscript benchmark/benchmark_imagenet_class_bias_full_grid.R \
  "${COMMON_ARGS[@]}" \
  --resume=true \
  2>&1 | tee -a "$LOG_FILE"
