from pathlib import Path

from docx import Document


ROOT = Path("/Users/stefano/Documents/GPUPLS/fastPLS_fresh_github")
SOURCE_DIR = ROOT / "artifacts/CMPB_rewrite_20260826_cycle112"
OUTDIR = ROOT / "artifacts/CMPB_rewrite_20260826_cycle113"


REPLACEMENTS = {
    "Regression returns continuous predictions. Classification uses argmax PLS-DA or LDA fitted to PLS scores. LDA uses pooled within-class covariance, Cholesky solves, class priors, and deterministic trace-scaled regularization only when factorization fails [17,18]. For imbalanced classification, cross-validation can select by balanced accuracy, defined as the unweighted mean of class-specific recalls; nested permutation testing uses the same selected endpoint rather than substituting dummy-response Q2. Permutation inference uses the finite Monte Carlo correction (b+1)/(B+1), where b is the number of successful null statistics at least as extreme as observed and B is the number of successful null fits. Independent observations are permuted by row; repeated observations identified by the grouping constraint are exchanged as complete blocks within equal-size exchangeability strata. Group sizes, within-group responses, and class frequencies are thereby preserved, while fold assignments and randomized-solver seeds remain fixed across observed and null analyses. Failed null fits are excluded from B and reported explicitly.":
    "For regression analyses, the fitted models produced continuous response estimates, whereas classification was performed by either maximum-score PLS-DA decoding or linear discriminant analysis (LDA) of the PLS scores. The LDA model used the pooled within-class covariance, class priors, and Cholesky-based linear solves, with deterministic trace-scaled regularization introduced only when factorization failed [17,18]. For imbalanced classification, model selection could instead maximize balanced accuracy, defined as the unweighted mean of class-specific recalls, and nested permutation testing evaluated the same selected endpoint rather than substituting dummy-response Q². Permutation inference applied the finite Monte Carlo correction (b+1)/(B+1), where b denotes the number of successful null statistics at least as extreme as the observed statistic and B the number of successful null fits. Independent observations were permuted by row, whereas repeated observations identified by the grouping constraint were exchanged as complete blocks within equal-size exchangeability strata. This procedure preserved group sizes, within-group responses, and class frequencies while holding fold assignments and randomized-solver seeds fixed across observed and null analyses. Failed null fits were excluded from B and reported explicitly.",

    "External timing used two predefined profiles. The minimum-output profile compared deterministic float64 SIMPLS while requiring the complete coefficient path, centering quantities, and final held-out predictions; scores, loadings, fitted-value arrays, and variance summaries were suppressed, with pls::simpls.fit called using stripped = TRUE. The public-workflow profile retained each implementation's ordinary model object and final predictions. Package and data loading preceded timing, no numerical warm-up was used, and every method-dataset repetition ran in a fresh process with one effective BLAS thread and a common 10,000-s timeout. Three repetitions were attempted for every pair; medians, IQRs, completed repetitions, failures, object sizes, and process RSS were retained.":
    "To distinguish numerical computation from the cost of constructing ordinary model objects, external timing was assessed under two predefined output profiles. The minimum-output profile compared deterministic float64 SIMPLS while requiring the complete coefficient path, centering quantities, and final held-out predictions; scores, loadings, fitted-value arrays, and variance summaries were suppressed, and pls::simpls.fit was called with stripped = TRUE. The public-workflow profile retained each implementation's ordinary model object together with the final predictions. Package and data loading were completed before timing, no numerical warm-up was applied, and each method-dataset repetition was executed in a fresh process with one effective BLAS thread and a common 10,000-s timeout. Three repetitions were attempted for every pair, and the analysis retained medians, interquartile ranges, numbers of completed repetitions, failures, object sizes, and process resident-set size.",

    "Two comparisons answered different questions. Numerical-kernel validation compared deterministic float64 fastPLS SIMPLS with de Jong SIMPLS in pls::simpls.fit. A separate archived-release CPU software comparison used fastPLS 0.99.25 and IKPLS 6.1.2 NumPy Algorithms 1 and 2 on identical stored splits, externally training-centred float64 predictors, centred one-hot responses, component counts, and final held-out predictions. Each route ran three times in a fresh process with one effective thread. Because IKPLS and SIMPLS are different estimators and retain different state, this is an end-to-end software comparison, not an estimator-matched benchmark. An earlier JAX/CUDA development comparison was not reproduced from the frozen environment and is excluded from central evidence.":
    "Numerical equivalence and software-level performance were assessed separately. Deterministic float64 fastPLS SIMPLS was first compared with the de Jong SIMPLS implementation in pls::simpls.fit to evaluate the numerical kernel. A separate archived-release CPU experiment compared fastPLS 0.99.25 with IKPLS 6.1.2 NumPy Algorithms 1 and 2 using identical stored splits, externally training-centred float64 predictors, centred one-hot responses, component counts, and final held-out predictions. Each route was executed three times in a fresh process with one effective thread. Because IKPLS and SIMPLS implement different estimators and retain different internal state, this experiment was interpreted as an end-to-end software comparison rather than an estimator-matched benchmark. An earlier JAX/CUDA development comparison could not be reproduced from the frozen environment and was therefore excluded from the central evidence.",

    "Workflow gains partly reflected output policy. On CIFAR-100, the compact fastPLS fit object was 1.39 MiB versus 7,777.99 MiB for ordinary pls::simpls.fit. Median complete-process peak RSS was 2,493.57 versus 13,415.25 MiB; from comparable 1,906.80 and 1,906.62 MiB pre-fit baselines, corrected peak increments were 586.77 versus 11,508.84 MiB. The theoretical largest retained dense object was the 0.586-MB final coefficient matrix for fastPLS and a 3,814.70-MB fitted or residual response path for pls::simpls.fit. These values describe the specified complete workflow, not isolated algorithmic workspace. When both methods retained complete coefficient paths, fit objects were 59.30 and 58.60 MiB, corrected increments were 69.22 and 127.13 MiB, and the speed-up was 1.21-fold. The broader package panel remains a workflow comparison with implementation-specific outputs (Supplementary Tables S10c-S10e).":
    "The magnitude of the observed workflow gains was influenced by differences in output retention. On CIFAR-100, the compact fastPLS fit object occupied 1.39 MiB, compared with 7,777.99 MiB for the ordinary pls::simpls.fit object. Median complete-process peak resident-set size was 2,493.57 and 13,415.25 MiB, respectively; after correction for comparable pre-fit baselines of 1,906.80 and 1,906.62 MiB, the corresponding peak increments were 586.77 and 11,508.84 MiB. The largest theoretically retained dense object was the 0.586-MB final coefficient matrix for fastPLS and a 3,814.70-MB fitted or residual response path for pls::simpls.fit. These measurements characterize the specified complete workflows rather than isolated algorithmic workspaces. When both implementations retained complete coefficient paths, the fit objects occupied 59.30 and 58.60 MiB, the corrected increments were 69.22 and 127.13 MiB, and the speed-up was 1.21-fold. The broader package panel therefore remains a workflow comparison involving implementation-specific outputs (Supplementary Tables S10c-S10e).",

    "Hardware acceleration remained route and shape dependent. In the archived real-dataset analysis, paired CPU/CUDA and CPU/Metal timing was interpreted only when the absolute predictive-metric difference was at most 0.005 and paired-prediction agreement was at least 0.995 (Figure 3). Among 44 CPU/CUDA pairs, 28 met both criteria and CUDA was faster in seven, including an 8.90-fold PLS-SVD ratio on CIFAR-100. Six of 12 CPU/Metal pairs met both criteria, but none favored Metal. Gray cells retain discordant routes without converting them into speed claims. A separate frozen-release SIMPLS-rSVD comparison is reported in Supplementary Figure S4 and Table S11. CPU IRLBA remains the deterministic numerical reference, and float32 does not uniformly improve runtime, process memory, or agreement (Supplementary Tables S8-S9).":
    "The computational benefit of hardware acceleration depended on both the execution route and workload dimensions. In the archived real-dataset analysis, paired CPU/CUDA and CPU/Metal timings were interpreted only when the absolute difference in predictive performance was at most 0.005 and paired-prediction agreement was at least 0.995 (Figure 3). Of the 44 CPU/CUDA pairs, 28 met both criteria and seven favored CUDA, including an 8.90-fold PLS-SVD runtime ratio on CIFAR-100. Six of the 12 CPU/Metal pairs met both criteria, but none favored Metal. Discordant routes remain visible as gray cells and were not converted into acceleration claims. A separate frozen-release SIMPLS-rSVD comparison is reported in Supplementary Figure S4 and Table S11. CPU IRLBA remains the deterministic numerical reference, and float32 did not uniformly improve runtime, process memory, or numerical agreement (Supplementary Tables S8-S9).",
}


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    document = Document(SOURCE_DIR / "fastPLS_CMPB_main_cycle112_0.99.25_20260826.docx")
    for old, new in REPLACEMENTS.items():
        matches = [paragraph for paragraph in document.paragraphs if paragraph.text == old]
        if len(matches) != 1:
            raise RuntimeError(f"Expected one paragraph match, found {len(matches)} for: {old[:90]}")
        matches[0].text = new
    document.save(OUTDIR / "fastPLS_CMPB_main_cycle113_0.99.25_20260826.docx")


if __name__ == "__main__":
    main()
