// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fastPLS.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pls_light
arma::mat pls_light(arma::mat Xtrain, arma::mat Ytrain, arma::mat Xtest, int ncomp);
RcppExport SEXP _fastPLS_pls_light(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP XtestSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_light(Xtrain, Ytrain, Xtest, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// ORTHOG
arma::mat ORTHOG(arma::mat& X, arma::mat& Y, arma::mat& T, int xm, int xn, int yn);
RcppExport SEXP _fastPLS_ORTHOG(SEXP XSEXP, SEXP YSEXP, SEXP TSEXP, SEXP xmSEXP, SEXP xnSEXP, SEXP ynSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< int >::type xn(xnSEXP);
    Rcpp::traits::input_parameter< int >::type yn(ynSEXP);
    rcpp_result_gen = Rcpp::wrap(ORTHOG(X, Y, T, xm, xn, yn));
    return rcpp_result_gen;
END_RCPP
}
// RQ
double RQ(arma::mat yData, arma::mat yPred);
RcppExport SEXP _fastPLS_RQ(SEXP yDataSEXP, SEXP yPredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type yData(yDataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yPred(yPredSEXP);
    rcpp_result_gen = Rcpp::wrap(RQ(yData, yPred));
    return rcpp_result_gen;
END_RCPP
}
// IRLB
List IRLB(const arma::mat& X, int nu, int work, int maxit, double tol, double eps, double svtol);
RcppExport SEXP _fastPLS_IRLB(SEXP XSEXP, SEXP nuSEXP, SEXP workSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP epsSEXP, SEXP svtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type work(workSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type svtol(svtolSEXP);
    rcpp_result_gen = Rcpp::wrap(IRLB(X, nu, work, maxit, tol, eps, svtol));
    return rcpp_result_gen;
END_RCPP
}
// transformy
arma::mat transformy(arma::ivec y);
RcppExport SEXP _fastPLS_transformy(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(transformy(y));
    return rcpp_result_gen;
END_RCPP
}
// has_cuda
bool has_cuda();
RcppExport SEXP _fastPLS_has_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_cuda());
    return rcpp_result_gen;
END_RCPP
}
// lda_cuda_native_available
bool lda_cuda_native_available();
RcppExport SEXP _fastPLS_lda_cuda_native_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lda_cuda_native_available());
    return rcpp_result_gen;
END_RCPP
}
// cuda_reset_workspace
void cuda_reset_workspace();
RcppExport SEXP _fastPLS_cuda_reset_workspace() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cuda_reset_workspace();
    return R_NilValue;
END_RCPP
}
// cuda_matrix_multiply
arma::mat cuda_matrix_multiply(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_cuda_matrix_multiply(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_matrix_multiply(A, B));
    return rcpp_result_gen;
END_RCPP
}
// candidate_knn_predict_cpp
Rcpp::List candidate_knn_predict_cpp(const arma::mat& Ttest_norm, const arma::mat& Ttrain_norm, const arma::ivec& y_codes, const arma::mat& centroids, const arma::vec& candidate_bias, int top_k, int top_m, int knn_k, double tau, double alpha);
RcppExport SEXP _fastPLS_candidate_knn_predict_cpp(SEXP Ttest_normSEXP, SEXP Ttrain_normSEXP, SEXP y_codesSEXP, SEXP centroidsSEXP, SEXP candidate_biasSEXP, SEXP top_kSEXP, SEXP top_mSEXP, SEXP knn_kSEXP, SEXP tauSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest_norm(Ttest_normSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain_norm(Ttrain_normSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type y_codes(y_codesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type candidate_bias(candidate_biasSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< int >::type top_m(top_mSEXP);
    Rcpp::traits::input_parameter< int >::type knn_k(knn_kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(candidate_knn_predict_cpp(Ttest_norm, Ttrain_norm, y_codes, centroids, candidate_bias, top_k, top_m, knn_k, tau, alpha));
    return rcpp_result_gen;
END_RCPP
}
// candidate_knn_predict_cuda
Rcpp::List candidate_knn_predict_cuda(const arma::mat& Ttest_norm, const arma::mat& Ttrain_norm, const arma::ivec& y_codes, const arma::mat& centroids, const arma::vec& candidate_bias, int top_k, int top_m, int knn_k, double tau, double alpha);
RcppExport SEXP _fastPLS_candidate_knn_predict_cuda(SEXP Ttest_normSEXP, SEXP Ttrain_normSEXP, SEXP y_codesSEXP, SEXP centroidsSEXP, SEXP candidate_biasSEXP, SEXP top_kSEXP, SEXP top_mSEXP, SEXP knn_kSEXP, SEXP tauSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest_norm(Ttest_normSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain_norm(Ttrain_normSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type y_codes(y_codesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type candidate_bias(candidate_biasSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< int >::type top_m(top_mSEXP);
    Rcpp::traits::input_parameter< int >::type knn_k(knn_kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(candidate_knn_predict_cuda(Ttest_norm, Ttrain_norm, y_codes, centroids, candidate_bias, top_k, top_m, knn_k, tau, alpha));
    return rcpp_result_gen;
END_RCPP
}
// cuda_thin_qr
arma::mat cuda_thin_qr(const arma::mat& A);
RcppExport SEXP _fastPLS_cuda_thin_qr(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_thin_qr(A));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_cpp
Rcpp::List lda_train_cpp(const arma::mat& Ttrain, const Rcpp::IntegerVector& y, int n_classes, double ridge);
RcppExport SEXP _fastPLS_lda_train_cpp(SEXP TtrainSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain(TtrainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_cpp(Ttrain, y, n_classes, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_cpp
Rcpp::List lda_train_prefix_cpp(const arma::mat& Ttrain, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_train_prefix_cpp(SEXP TtrainSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain(TtrainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_cpp(Ttrain, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_train_prefix_cpp
Rcpp::List lda_project_train_prefix_cpp(const arma::mat& Xtrain, const arma::mat& R, const arma::rowvec& offset, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_project_train_prefix_cpp(SEXP XtrainSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_train_prefix_cpp(Xtrain, R, offset, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_cuda
Rcpp::List lda_train_prefix_cuda(const arma::mat& Ttrain, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_train_prefix_cuda(SEXP TtrainSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain(TtrainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_cuda(Ttrain, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_train_prefix_cuda
Rcpp::List lda_project_train_prefix_cuda(const arma::mat& Xtrain, const arma::mat& R, const arma::rowvec& offset, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_project_train_prefix_cuda(SEXP XtrainSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_train_prefix_cuda(Xtrain, R, offset, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_cpp
Rcpp::List lda_predict_cpp(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_cpp(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_cpp(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_labels_cpp
Rcpp::IntegerVector lda_predict_labels_cpp(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_labels_cpp(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_labels_cpp(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_predict_labels_cpp
Rcpp::IntegerVector lda_project_predict_labels_cpp(const arma::mat& Xtest, const arma::mat& R, const arma::rowvec& offset, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_project_predict_labels_cpp(SEXP XtestSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_predict_labels_cpp(Xtest, R, offset, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_cuda
Rcpp::List lda_predict_cuda(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_cuda(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_cuda(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_labels_cuda
Rcpp::IntegerVector lda_predict_labels_cuda(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_labels_cuda(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_labels_cuda(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_predict_cuda
Rcpp::List lda_project_predict_cuda(const arma::mat& Xtest, const arma::mat& R, const arma::rowvec& offset, const Rcpp::List& lda, bool return_scores);
RcppExport SEXP _fastPLS_lda_project_predict_cuda(SEXP XtestSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ldaSEXP, SEXP return_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_predict_cuda(Xtest, R, offset, lda, return_scores));
    return rcpp_result_gen;
END_RCPP
}
// truncated_svd_debug
Rcpp::List truncated_svd_debug(const arma::mat& A, int k, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, bool left_only);
RcppExport SEXP _fastPLS_truncated_svd_debug(SEXP ASEXP, SEXP kSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP left_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type left_only(left_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_svd_debug(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2
List pls_model2(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast
List pls_model2_fast(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_gpu
List pls_model2_fast_gpu(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_gpu(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict
List pls_predict(List& model, arma::mat Xtest, bool proj);
RcppExport SEXP _fastPLS_pls_predict(SEXP modelSEXP, SEXP XtestSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict(model, Xtest, proj));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict_flash_cuda
List pls_predict_flash_cuda(List& model, arma::mat Xtest, bool proj);
RcppExport SEXP _fastPLS_pls_predict_flash_cuda(SEXP modelSEXP, SEXP XtestSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict_flash_cuda(model, Xtest, proj));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict_flash_cpu
List pls_predict_flash_cpu(List& model, arma::mat Xtest, bool proj, int block_size);
RcppExport SEXP _fastPLS_pls_predict_flash_cpu(SEXP modelSEXP, SEXP XtestSEXP, SEXP projSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict_flash_cpu(model, Xtest, proj, block_size));
    return rcpp_result_gen;
END_RCPP
}
// pls_class_predict_topk_cpp
List pls_class_predict_topk_cpp(List& model, arma::mat Xtest, arma::mat class_bias, int top_k, bool proj, int block_size);
RcppExport SEXP _fastPLS_pls_class_predict_topk_cpp(SEXP modelSEXP, SEXP XtestSEXP, SEXP class_biasSEXP, SEXP top_kSEXP, SEXP projSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type class_bias(class_biasSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_class_predict_topk_cpp(model, Xtest, class_bias, top_k, proj, block_size));
    return rcpp_result_gen;
END_RCPP
}
// pls_class_predict_topk_cuda
List pls_class_predict_topk_cuda(List& model, arma::mat Xtest, arma::mat class_bias, int top_k, bool proj);
RcppExport SEXP _fastPLS_pls_class_predict_topk_cuda(SEXP modelSEXP, SEXP XtestSEXP, SEXP class_biasSEXP, SEXP top_kSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type class_bias(class_biasSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_class_predict_topk_cuda(model, Xtest, class_bias, top_k, proj));
    return rcpp_result_gen;
END_RCPP
}
// kernel_matrix_cpp
arma::mat kernel_matrix_cpp(const arma::mat& X1, const arma::mat& X2, const int kernel, const double gamma, const int degree, const double coef0);
RcppExport SEXP _fastPLS_kernel_matrix_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const double >::type coef0(coef0SEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_cpp(X1, X2, kernel, gamma, degree, coef0));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_train_cpp
Rcpp::List center_kernel_train_cpp(const arma::mat& K);
RcppExport SEXP _fastPLS_center_kernel_train_cpp(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_train_cpp(K));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_test_cpp
arma::mat center_kernel_test_cpp(const arma::mat& Ktest, const arma::rowvec& train_col_means, const double train_grand_mean);
RcppExport SEXP _fastPLS_center_kernel_test_cpp(SEXP KtestSEXP, SEXP train_col_meansSEXP, SEXP train_grand_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ktest(KtestSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type train_col_means(train_col_meansSEXP);
    Rcpp::traits::input_parameter< const double >::type train_grand_mean(train_grand_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_test_cpp(Ktest, train_col_means, train_grand_mean));
    return rcpp_result_gen;
END_RCPP
}
// opls_filter_cpp
Rcpp::List opls_filter_cpp(arma::mat X, arma::mat Y, const int north, const int scaling);
RcppExport SEXP _fastPLS_opls_filter_cpp(SEXP XSEXP, SEXP YSEXP, SEXP northSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type north(northSEXP);
    Rcpp::traits::input_parameter< const int >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_filter_cpp(X, Y, north, scaling));
    return rcpp_result_gen;
END_RCPP
}
// opls_apply_filter_cpp
arma::mat opls_apply_filter_cpp(arma::mat X, const arma::rowvec& mX, const arma::rowvec& vX, const arma::mat& W_orth, const arma::mat& P_orth);
RcppExport SEXP _fastPLS_opls_apply_filter_cpp(SEXP XSEXP, SEXP mXSEXP, SEXP vXSEXP, SEXP W_orthSEXP, SEXP P_orthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_orth(W_orthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P_orth(P_orthSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_apply_filter_cpp(X, mX, vX, W_orth, P_orth));
    return rcpp_result_gen;
END_RCPP
}
// unic
int unic(arma::mat x);
RcppExport SEXP _fastPLS_unic(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(unic(x));
    return rcpp_result_gen;
END_RCPP
}
// optim_pls_cv
List optim_pls_cv(arma::mat Xdata, arma::mat Ydata, arma::ivec constrain, arma::ivec ncomp, int scaling, int kfold, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_optim_pls_cv(SEXP XdataSEXP, SEXP YdataSEXP, SEXP constrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP kfoldSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_pls_cv(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// double_pls_cv
List double_pls_cv(arma::mat Xdata, arma::mat Ydata, arma::ivec ncomp, arma::ivec constrain, int scaling, int kfold_inner, int kfold_outer, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_double_pls_cv(SEXP XdataSEXP, SEXP YdataSEXP, SEXP ncompSEXP, SEXP constrainSEXP, SEXP scalingSEXP, SEXP kfold_innerSEXP, SEXP kfold_outerSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold_inner(kfold_innerSEXP);
    Rcpp::traits::input_parameter< int >::type kfold_outer(kfold_outerSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(double_pls_cv(Xdata, Ydata, ncomp, constrain, scaling, kfold_inner, kfold_outer, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1
List pls_model1(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_rsvd_xprod_precision
List pls_model1_rsvd_xprod_precision(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, int xprod_precision);
RcppExport SEXP _fastPLS_pls_model1_rsvd_xprod_precision(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP xprod_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type xprod_precision(xprod_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_rsvd_xprod_precision(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_rsvd_xprod_precision
List pls_model2_fast_rsvd_xprod_precision(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, int xprod_precision);
RcppExport SEXP _fastPLS_pls_model2_fast_rsvd_xprod_precision(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP xprod_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type xprod_precision(xprod_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_rsvd_xprod_precision(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_gpu
List pls_model1_gpu(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_gpu(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_gpu_implicit_xprod
List pls_model1_gpu_implicit_xprod(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1_gpu_implicit_xprod(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_gpu_implicit_xprod(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_lda_gpu_native
List pls_lda_gpu_native(arma::mat Xtrain, arma::mat Ytrain, arma::ivec y, arma::mat Xtest, arma::ivec ncomp, int n_classes, int method, int scaling, bool xprod, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, double lda_ridge);
RcppExport SEXP _fastPLS_pls_lda_gpu_native(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ySEXP, SEXP XtestSEXP, SEXP ncompSEXP, SEXP n_classesSEXP, SEXP methodSEXP, SEXP scalingSEXP, SEXP xprodSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP lda_ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type xprod(xprodSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type lda_ridge(lda_ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_lda_gpu_native(Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge));
    return rcpp_result_gen;
END_RCPP
}
// pls_cv_predict_compiled
List pls_cv_predict_compiled(arma::mat Xdata, arma::mat Ydata, arma::ivec constrain, arma::ivec ncomp, int scaling, int kfold, int method, int backend, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, bool classification, int n_response, bool xprod, int opls_north, bool return_scores, arma::mat class_codes, int classifier, double lda_ridge, int candidate_knn_k, double candidate_tau, double candidate_alpha, int candidate_top_m);
RcppExport SEXP _fastPLS_pls_cv_predict_compiled(SEXP XdataSEXP, SEXP YdataSEXP, SEXP constrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP kfoldSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP classificationSEXP, SEXP n_responseSEXP, SEXP xprodSEXP, SEXP opls_northSEXP, SEXP return_scoresSEXP, SEXP class_codesSEXP, SEXP classifierSEXP, SEXP lda_ridgeSEXP, SEXP candidate_knn_kSEXP, SEXP candidate_tauSEXP, SEXP candidate_alphaSEXP, SEXP candidate_top_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type classification(classificationSEXP);
    Rcpp::traits::input_parameter< int >::type n_response(n_responseSEXP);
    Rcpp::traits::input_parameter< bool >::type xprod(xprodSEXP);
    Rcpp::traits::input_parameter< int >::type opls_north(opls_northSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type class_codes(class_codesSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< double >::type lda_ridge(lda_ridgeSEXP);
    Rcpp::traits::input_parameter< int >::type candidate_knn_k(candidate_knn_kSEXP);
    Rcpp::traits::input_parameter< double >::type candidate_tau(candidate_tauSEXP);
    Rcpp::traits::input_parameter< double >::type candidate_alpha(candidate_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type candidate_top_m(candidate_top_mSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_cv_predict_compiled(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, candidate_knn_k, candidate_tau, candidate_alpha, candidate_top_m));
    return rcpp_result_gen;
END_RCPP
}
// has_metal
bool has_metal();
RcppExport SEXP _fastPLS_has_metal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_metal());
    return rcpp_result_gen;
END_RCPP
}
// metal_matrix_multiply_cpp
arma::mat metal_matrix_multiply_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_metal_matrix_multiply_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_matrix_multiply_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// metal_crossprod_cpp
arma::mat metal_crossprod_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_metal_crossprod_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_crossprod_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// metal_simpls_resident_cpp
Rcpp::List metal_simpls_resident_cpp(const arma::mat& X, const arma::mat& Y, int ncomp, int power_iters, int seed);
RcppExport SEXP _fastPLS_metal_simpls_resident_cpp(SEXP XSEXP, SEXP YSEXP, SEXP ncompSEXP, SEXP power_itersSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type power_iters(power_itersSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_simpls_resident_cpp(X, Y, ncomp, power_iters, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastPLS_pls_light", (DL_FUNC) &_fastPLS_pls_light, 4},
    {"_fastPLS_ORTHOG", (DL_FUNC) &_fastPLS_ORTHOG, 6},
    {"_fastPLS_RQ", (DL_FUNC) &_fastPLS_RQ, 2},
    {"_fastPLS_IRLB", (DL_FUNC) &_fastPLS_IRLB, 7},
    {"_fastPLS_transformy", (DL_FUNC) &_fastPLS_transformy, 1},
    {"_fastPLS_has_cuda", (DL_FUNC) &_fastPLS_has_cuda, 0},
    {"_fastPLS_lda_cuda_native_available", (DL_FUNC) &_fastPLS_lda_cuda_native_available, 0},
    {"_fastPLS_cuda_reset_workspace", (DL_FUNC) &_fastPLS_cuda_reset_workspace, 0},
    {"_fastPLS_cuda_matrix_multiply", (DL_FUNC) &_fastPLS_cuda_matrix_multiply, 2},
    {"_fastPLS_candidate_knn_predict_cpp", (DL_FUNC) &_fastPLS_candidate_knn_predict_cpp, 10},
    {"_fastPLS_candidate_knn_predict_cuda", (DL_FUNC) &_fastPLS_candidate_knn_predict_cuda, 10},
    {"_fastPLS_cuda_thin_qr", (DL_FUNC) &_fastPLS_cuda_thin_qr, 1},
    {"_fastPLS_lda_train_cpp", (DL_FUNC) &_fastPLS_lda_train_cpp, 4},
    {"_fastPLS_lda_train_prefix_cpp", (DL_FUNC) &_fastPLS_lda_train_prefix_cpp, 5},
    {"_fastPLS_lda_project_train_prefix_cpp", (DL_FUNC) &_fastPLS_lda_project_train_prefix_cpp, 7},
    {"_fastPLS_lda_train_prefix_cuda", (DL_FUNC) &_fastPLS_lda_train_prefix_cuda, 5},
    {"_fastPLS_lda_project_train_prefix_cuda", (DL_FUNC) &_fastPLS_lda_project_train_prefix_cuda, 7},
    {"_fastPLS_lda_predict_cpp", (DL_FUNC) &_fastPLS_lda_predict_cpp, 2},
    {"_fastPLS_lda_predict_labels_cpp", (DL_FUNC) &_fastPLS_lda_predict_labels_cpp, 2},
    {"_fastPLS_lda_project_predict_labels_cpp", (DL_FUNC) &_fastPLS_lda_project_predict_labels_cpp, 4},
    {"_fastPLS_lda_predict_cuda", (DL_FUNC) &_fastPLS_lda_predict_cuda, 2},
    {"_fastPLS_lda_predict_labels_cuda", (DL_FUNC) &_fastPLS_lda_predict_labels_cuda, 2},
    {"_fastPLS_lda_project_predict_cuda", (DL_FUNC) &_fastPLS_lda_project_predict_cuda, 5},
    {"_fastPLS_truncated_svd_debug", (DL_FUNC) &_fastPLS_truncated_svd_debug, 8},
    {"_fastPLS_pls_model2", (DL_FUNC) &_fastPLS_pls_model2, 10},
    {"_fastPLS_pls_model2_fast", (DL_FUNC) &_fastPLS_pls_model2_fast, 10},
    {"_fastPLS_pls_model2_fast_gpu", (DL_FUNC) &_fastPLS_pls_model2_fast_gpu, 10},
    {"_fastPLS_pls_predict", (DL_FUNC) &_fastPLS_pls_predict, 3},
    {"_fastPLS_pls_predict_flash_cuda", (DL_FUNC) &_fastPLS_pls_predict_flash_cuda, 3},
    {"_fastPLS_pls_predict_flash_cpu", (DL_FUNC) &_fastPLS_pls_predict_flash_cpu, 4},
    {"_fastPLS_pls_class_predict_topk_cpp", (DL_FUNC) &_fastPLS_pls_class_predict_topk_cpp, 6},
    {"_fastPLS_pls_class_predict_topk_cuda", (DL_FUNC) &_fastPLS_pls_class_predict_topk_cuda, 5},
    {"_fastPLS_kernel_matrix_cpp", (DL_FUNC) &_fastPLS_kernel_matrix_cpp, 6},
    {"_fastPLS_center_kernel_train_cpp", (DL_FUNC) &_fastPLS_center_kernel_train_cpp, 1},
    {"_fastPLS_center_kernel_test_cpp", (DL_FUNC) &_fastPLS_center_kernel_test_cpp, 3},
    {"_fastPLS_opls_filter_cpp", (DL_FUNC) &_fastPLS_opls_filter_cpp, 4},
    {"_fastPLS_opls_apply_filter_cpp", (DL_FUNC) &_fastPLS_opls_apply_filter_cpp, 5},
    {"_fastPLS_unic", (DL_FUNC) &_fastPLS_unic, 1},
    {"_fastPLS_optim_pls_cv", (DL_FUNC) &_fastPLS_optim_pls_cv, 12},
    {"_fastPLS_double_pls_cv", (DL_FUNC) &_fastPLS_double_pls_cv, 13},
    {"_fastPLS_pls_model1", (DL_FUNC) &_fastPLS_pls_model1, 10},
    {"_fastPLS_pls_model1_rsvd_xprod_precision", (DL_FUNC) &_fastPLS_pls_model1_rsvd_xprod_precision, 10},
    {"_fastPLS_pls_model2_fast_rsvd_xprod_precision", (DL_FUNC) &_fastPLS_pls_model2_fast_rsvd_xprod_precision, 10},
    {"_fastPLS_pls_model1_gpu", (DL_FUNC) &_fastPLS_pls_model1_gpu, 9},
    {"_fastPLS_pls_model1_gpu_implicit_xprod", (DL_FUNC) &_fastPLS_pls_model1_gpu_implicit_xprod, 9},
    {"_fastPLS_pls_lda_gpu_native", (DL_FUNC) &_fastPLS_pls_lda_gpu_native, 15},
    {"_fastPLS_pls_cv_predict_compiled", (DL_FUNC) &_fastPLS_pls_cv_predict_compiled, 25},
    {"_fastPLS_has_metal", (DL_FUNC) &_fastPLS_has_metal, 0},
    {"_fastPLS_metal_matrix_multiply_cpp", (DL_FUNC) &_fastPLS_metal_matrix_multiply_cpp, 2},
    {"_fastPLS_metal_crossprod_cpp", (DL_FUNC) &_fastPLS_metal_crossprod_cpp, 2},
    {"_fastPLS_metal_simpls_resident_cpp", (DL_FUNC) &_fastPLS_metal_simpls_resident_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastPLS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
