// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fastPLS.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pls_light
arma::mat pls_light(arma::mat Xtrain, arma::mat Ytrain, arma::mat Xtest, int ncomp);
RcppExport SEXP _fastPLS_pls_light(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP XtestSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_light(Xtrain, Ytrain, Xtest, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// ORTHOG
arma::mat ORTHOG(arma::mat& X, arma::mat& Y, arma::mat& T, int xm, int xn, int yn);
RcppExport SEXP _fastPLS_ORTHOG(SEXP XSEXP, SEXP YSEXP, SEXP TSEXP, SEXP xmSEXP, SEXP xnSEXP, SEXP ynSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< int >::type xn(xnSEXP);
    Rcpp::traits::input_parameter< int >::type yn(ynSEXP);
    rcpp_result_gen = Rcpp::wrap(ORTHOG(X, Y, T, xm, xn, yn));
    return rcpp_result_gen;
END_RCPP
}
// RQ
double RQ(arma::mat yData, arma::mat yPred);
RcppExport SEXP _fastPLS_RQ(SEXP yDataSEXP, SEXP yPredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type yData(yDataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yPred(yPredSEXP);
    rcpp_result_gen = Rcpp::wrap(RQ(yData, yPred));
    return rcpp_result_gen;
END_RCPP
}
// IRLB
List IRLB(arma::mat& X, int nu, int work, int maxit, double tol, double eps, double svtol);
RcppExport SEXP _fastPLS_IRLB(SEXP XSEXP, SEXP nuSEXP, SEXP workSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP epsSEXP, SEXP svtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type work(workSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type svtol(svtolSEXP);
    rcpp_result_gen = Rcpp::wrap(IRLB(X, nu, work, maxit, tol, eps, svtol));
    return rcpp_result_gen;
END_RCPP
}
// transformy
arma::mat transformy(arma::ivec y);
RcppExport SEXP _fastPLS_transformy(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(transformy(y));
    return rcpp_result_gen;
END_RCPP
}
// has_cuda
bool has_cuda();
RcppExport SEXP _fastPLS_has_cuda() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_cuda());
    return rcpp_result_gen;
END_RCPP
}
// cuda_reset_workspace
void cuda_reset_workspace();
RcppExport SEXP _fastPLS_cuda_reset_workspace() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cuda_reset_workspace();
    return R_NilValue;
END_RCPP
}
// truncated_svd_debug
Rcpp::List truncated_svd_debug(const arma::mat& A, int k, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, bool left_only);
RcppExport SEXP _fastPLS_truncated_svd_debug(SEXP ASEXP, SEXP kSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP left_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type left_only(left_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_svd_debug(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2
List pls_model2(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast
List pls_model2_fast(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_gpu
List pls_model2_fast_gpu(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_gpu(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict
List pls_predict(List& model, arma::mat Xtest, bool proj);
RcppExport SEXP _fastPLS_pls_predict(SEXP modelSEXP, SEXP XtestSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict(model, Xtest, proj));
    return rcpp_result_gen;
END_RCPP
}
// unic
int unic(arma::mat x);
RcppExport SEXP _fastPLS_unic(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(unic(x));
    return rcpp_result_gen;
END_RCPP
}
// optim_pls_cv
List optim_pls_cv(arma::mat Xdata, arma::mat Ydata, arma::ivec constrain, arma::ivec ncomp, int scaling, int kfold, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_optim_pls_cv(SEXP XdataSEXP, SEXP YdataSEXP, SEXP constrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP kfoldSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_pls_cv(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// double_pls_cv
List double_pls_cv(arma::mat Xdata, arma::mat Ydata, arma::ivec ncomp, arma::ivec constrain, int scaling, int kfold_inner, int kfold_outer, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_double_pls_cv(SEXP XdataSEXP, SEXP YdataSEXP, SEXP ncompSEXP, SEXP constrainSEXP, SEXP scalingSEXP, SEXP kfold_innerSEXP, SEXP kfold_outerSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold_inner(kfold_innerSEXP);
    Rcpp::traits::input_parameter< int >::type kfold_outer(kfold_outerSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(double_pls_cv(Xdata, Ydata, ncomp, constrain, scaling, kfold_inner, kfold_outer, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1
List pls_model1(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_gpu
List pls_model1_gpu(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_gpu(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastPLS_pls_light", (DL_FUNC) &_fastPLS_pls_light, 4},
    {"_fastPLS_ORTHOG", (DL_FUNC) &_fastPLS_ORTHOG, 6},
    {"_fastPLS_RQ", (DL_FUNC) &_fastPLS_RQ, 2},
    {"_fastPLS_IRLB", (DL_FUNC) &_fastPLS_IRLB, 7},
    {"_fastPLS_transformy", (DL_FUNC) &_fastPLS_transformy, 1},
    {"_fastPLS_has_cuda", (DL_FUNC) &_fastPLS_has_cuda, 0},
    {"_fastPLS_cuda_reset_workspace", (DL_FUNC) &_fastPLS_cuda_reset_workspace, 0},
    {"_fastPLS_truncated_svd_debug", (DL_FUNC) &_fastPLS_truncated_svd_debug, 8},
    {"_fastPLS_pls_model2", (DL_FUNC) &_fastPLS_pls_model2, 10},
    {"_fastPLS_pls_model2_fast", (DL_FUNC) &_fastPLS_pls_model2_fast, 10},
    {"_fastPLS_pls_model2_fast_gpu", (DL_FUNC) &_fastPLS_pls_model2_fast_gpu, 10},
    {"_fastPLS_pls_predict", (DL_FUNC) &_fastPLS_pls_predict, 3},
    {"_fastPLS_unic", (DL_FUNC) &_fastPLS_unic, 1},
    {"_fastPLS_optim_pls_cv", (DL_FUNC) &_fastPLS_optim_pls_cv, 12},
    {"_fastPLS_double_pls_cv", (DL_FUNC) &_fastPLS_double_pls_cv, 13},
    {"_fastPLS_pls_model1", (DL_FUNC) &_fastPLS_pls_model1, 10},
    {"_fastPLS_pls_model1_gpu", (DL_FUNC) &_fastPLS_pls_model1_gpu, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastPLS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
