# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

label_crossprod_scaled_cpp <- function(XtrainSEXP, y, n_classes, scaling) {
    .Call(`_fastPLS_label_crossprod_scaled_cpp`, XtrainSEXP, y, n_classes, scaling)
}

RQ <- function(yData, yPred) {
    .Call(`_fastPLS_RQ`, yData, yPred)
}

transformy <- function(y) {
    .Call(`_fastPLS_transformy`, y)
}

kernel_matrix_float32_cpp <- function(X1SEXP, X2SEXP, kernel, gamma, degree, coef0, backend) {
    .Call(`_fastPLS_kernel_matrix_float32_cpp`, X1SEXP, X2SEXP, kernel, gamma, degree, coef0, backend)
}

center_kernel_train_float32_cpp <- function(KSEXP) {
    .Call(`_fastPLS_center_kernel_train_float32_cpp`, KSEXP)
}

center_kernel_test_float32_cpp <- function(KtestSEXP, trainColMeansSEXP, train_grand_mean) {
    .Call(`_fastPLS_center_kernel_test_float32_cpp`, KtestSEXP, trainColMeansSEXP, train_grand_mean)
}

opls_filter_float32_cpp <- function(XSEXP, YSEXP, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_opls_filter_float32_cpp`, XSEXP, YSEXP, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

opls_apply_filter_float32_cpp <- function(XSEXP, mXSEXP, vXSEXP, WSEXP, PSEXP, backend) {
    .Call(`_fastPLS_opls_apply_filter_float32_cpp`, XSEXP, mXSEXP, vXSEXP, WSEXP, PSEXP, backend)
}

lda_train_prefix_float32_cpp <- function(TtrainSEXP, y, n_classes, ncomp) {
    .Call(`_fastPLS_lda_train_prefix_float32_cpp`, TtrainSEXP, y, n_classes, ncomp)
}

lda_predict_float32_cpp <- function(TtestSEXP, lda, return_scores = TRUE) {
    .Call(`_fastPLS_lda_predict_float32_cpp`, TtestSEXP, lda, return_scores)
}

lda_train_prefix_float32_cuda <- function(TtrainSEXP, y, n_classes, ncomp) {
    .Call(`_fastPLS_lda_train_prefix_float32_cuda`, TtrainSEXP, y, n_classes, ncomp)
}

lda_predict_float32_cuda <- function(TtestSEXP, lda, return_scores = TRUE) {
    .Call(`_fastPLS_lda_predict_float32_cuda`, TtestSEXP, lda, return_scores)
}

cuda_float32_rsvd_sample_cpp <- function(ASEXP, l, power_iters, seed) {
    .Call(`_fastPLS_cuda_float32_rsvd_sample_cpp`, ASEXP, l, power_iters, seed)
}

metal_float32_matrix_multiply_cpp <- function(ASEXP, BSEXP, transpose_left = FALSE, transpose_right = FALSE) {
    .Call(`_fastPLS_metal_float32_matrix_multiply_cpp`, ASEXP, BSEXP, transpose_left, transpose_right)
}

metal_float32_rsvd_sample_cpp <- function(ASEXP, l, power_iters, seed) {
    .Call(`_fastPLS_metal_float32_rsvd_sample_cpp`, ASEXP, l, power_iters, seed)
}

metal_float32_irlba_cpp <- function(ASEXP, k, seed, left_only = FALSE) {
    .Call(`_fastPLS_metal_float32_irlba_cpp`, ASEXP, k, seed, left_only)
}

fastsvd_float32_cpp <- function(ASEXP, k, backend, svd_method, rsvd_oversample, rsvd_power, seed, left_only = FALSE) {
    .Call(`_fastPLS_fastsvd_float32_cpp`, ASEXP, k, backend, svd_method, rsvd_oversample, rsvd_power, seed, left_only)
}

pls_float32_cpu_cpp <- function(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_pls_float32_cpu_cpp`, XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

pls_float32_labels_cpp <- function(XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_pls_float32_labels_cpp`, XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

float32_argmax_cpp <- function(scoresSEXP) {
    .Call(`_fastPLS_float32_argmax_cpp`, scoresSEXP)
}

has_cuda <- function() {
    .Call(`_fastPLS_has_cuda`)
}

lda_cuda_native_available <- function() {
    .Call(`_fastPLS_lda_cuda_native_available`)
}

cuda_reset_workspace <- function() {
    invisible(.Call(`_fastPLS_cuda_reset_workspace`))
}

cuda_matrix_multiply <- function(A, B) {
    .Call(`_fastPLS_cuda_matrix_multiply`, A, B)
}

cuda_thin_qr <- function(A) {
    .Call(`_fastPLS_cuda_thin_qr`, A)
}

lda_train_prefix_cpp <- function(Ttrain, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_train_prefix_cpp`, Ttrain, y, n_classes, ncomp, ridge)
}

lda_train_moments_prefix_cpp <- function(gram, class_sums, counts, n, ncomp) {
    .Call(`_fastPLS_lda_train_moments_prefix_cpp`, gram, class_sums, counts, n, ncomp)
}

lda_project_train_prefix_cpp <- function(Xtrain, R, offset, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_project_train_prefix_cpp`, Xtrain, R, offset, y, n_classes, ncomp, ridge)
}

lda_train_prefix_cuda <- function(Ttrain, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_train_prefix_cuda`, Ttrain, y, n_classes, ncomp, ridge)
}

lda_project_train_prefix_cuda <- function(Xtrain, R, offset, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_project_train_prefix_cuda`, Xtrain, R, offset, y, n_classes, ncomp, ridge)
}

lda_predict_cpp <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_cpp`, Ttest, lda)
}

lda_predict_labels_cpp <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_labels_cpp`, Ttest, lda)
}

lda_project_predict_labels_cpp <- function(Xtest, R, offset, lda) {
    .Call(`_fastPLS_lda_project_predict_labels_cpp`, Xtest, R, offset, lda)
}

lda_predict_cuda <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_cuda`, Ttest, lda)
}

lda_predict_labels_cuda <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_labels_cuda`, Ttest, lda)
}

lda_project_predict_cuda <- function(Xtest, R, offset, lda, return_scores = FALSE) {
    .Call(`_fastPLS_lda_project_predict_cuda`, Xtest, R, offset, lda, return_scores)
}

truncated_svd_debug <- function(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only) {
    .Call(`_fastPLS_truncated_svd_debug`, A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only)
}

pls_model2 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast_gpu <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast_gpu`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast_gpu_labels <- function(XtrainSEXP, y, n_classes, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast_gpu_labels`, XtrainSEXP, y, n_classes, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_predict <- function(model, Xtest, proj) {
    .Call(`_fastPLS_pls_predict`, model, Xtest, proj)
}

pls_predict_flash_cuda <- function(model, Xtest, proj) {
    .Call(`_fastPLS_pls_predict_flash_cuda`, model, Xtest, proj)
}

pls_predict_flash_cpu <- function(model, Xtest, proj, block_size) {
    .Call(`_fastPLS_pls_predict_flash_cpu`, model, Xtest, proj, block_size)
}

pls_class_predict_topk_cpp <- function(model, Xtest, top_k, proj, block_size) {
    .Call(`_fastPLS_pls_class_predict_topk_cpp`, model, Xtest, top_k, proj, block_size)
}

pls_class_predict_topk_cuda <- function(model, Xtest, top_k, proj) {
    .Call(`_fastPLS_pls_class_predict_topk_cuda`, model, Xtest, top_k, proj)
}

kernel_matrix_cpp <- function(X1, X2, kernel, gamma, degree, coef0) {
    .Call(`_fastPLS_kernel_matrix_cpp`, X1, X2, kernel, gamma, degree, coef0)
}

center_kernel_train_cpp <- function(K) {
    .Call(`_fastPLS_center_kernel_train_cpp`, K)
}

center_kernel_test_cpp <- function(Ktest, train_col_means, train_grand_mean) {
    .Call(`_fastPLS_center_kernel_test_cpp`, Ktest, train_col_means, train_grand_mean)
}

opls_filter_cpp <- function(X, Y, north, scaling) {
    .Call(`_fastPLS_opls_filter_cpp`, X, Y, north, scaling)
}

opls_apply_filter_cpp <- function(X, mX, vX, W_orth, P_orth) {
    .Call(`_fastPLS_opls_apply_filter_cpp`, X, mX, vX, W_orth, P_orth)
}

single_pls_cv_cpp <- function(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_single_pls_cv_cpp`, Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1_rsvd_xprod_precision <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision) {
    .Call(`_fastPLS_pls_model1_rsvd_xprod_precision`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision)
}

pls_model2_fast_rsvd_xprod_precision <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision) {
    .Call(`_fastPLS_pls_model2_fast_rsvd_xprod_precision`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision)
}

pls_model1_gpu <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1_gpu`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1_gpu_implicit_xprod <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1_gpu_implicit_xprod`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_lda_gpu_native <- function(Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge) {
    .Call(`_fastPLS_pls_lda_gpu_native`, Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge)
}

pls_cv_predict_compiled <- function(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, store_predictions, metric_id) {
    .Call(`_fastPLS_pls_cv_predict_compiled`, Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, store_predictions, metric_id)
}

fastpls_cpp_core_rsvd <- function(A, k, oversample = 10L, power = 1L, seed = 1L, use_float = FALSE) {
    .Call(`_fastPLS_fastpls_cpp_core_rsvd`, A, k, oversample, power, seed, use_float)
}

fastpls_cpp_core_plssvd <- function(X, Y, ncomp, oversample = 10L, power = 1L, seed = 1L, use_float = FALSE) {
    .Call(`_fastPLS_fastpls_cpp_core_plssvd`, X, Y, ncomp, oversample, power, seed, use_float)
}

fastpls_cpp_core_simpls <- function(X, Y, ncomp, oversample = 10L, power = 1L, seed = 1L, use_float = FALSE) {
    .Call(`_fastPLS_fastpls_cpp_core_simpls`, X, Y, ncomp, oversample, power, seed, use_float)
}

has_metal <- function() {
    .Call(`_fastPLS_has_metal`)
}

metal_matrix_multiply_cpp <- function(A, B) {
    .Call(`_fastPLS_metal_matrix_multiply_cpp`, A, B)
}

metal_crossprod_cpp <- function(A, B) {
    .Call(`_fastPLS_metal_crossprod_cpp`, A, B)
}

metal_simpls_resident_cpp <- function(X, Y, ncomp, power_iters = 2L, seed = 1L) {
    .Call(`_fastPLS_metal_simpls_resident_cpp`, X, Y, ncomp, power_iters, seed)
}

