# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Export Header-only Function into R
NULL

pls_light <- function(Xtrain, Ytrain, Xtest, ncomp) {
    .Call(`_fastPLS_pls_light`, Xtrain, Ytrain, Xtest, ncomp)
}

ORTHOG <- function(X, Y, T, xm, xn, yn) {
    .Call(`_fastPLS_ORTHOG`, X, Y, T, xm, xn, yn)
}

RQ <- function(yData, yPred) {
    .Call(`_fastPLS_RQ`, yData, yPred)
}

IRLB <- function(X, nu, work, maxit, tol, eps, svtol) {
    .Call(`_fastPLS_IRLB`, X, nu, work, maxit, tol, eps, svtol)
}

transformy <- function(y) {
    .Call(`_fastPLS_transformy`, y)
}

has_cuda <- function() {
    .Call(`_fastPLS_has_cuda`)
}

truncated_svd_debug <- function(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only) {
    .Call(`_fastPLS_truncated_svd_debug`, A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only)
}

pls_model2 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_predict <- function(model, Xtest, proj) {
    .Call(`_fastPLS_pls_predict`, model, Xtest, proj)
}

unic <- function(x) {
    .Call(`_fastPLS_unic`, x)
}

optim_pls_cv <- function(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_optim_pls_cv`, Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

double_pls_cv <- function(Xdata, Ydata, ncomp, constrain, scaling, kfold_inner, kfold_outer, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_double_pls_cv`, Xdata, Ydata, ncomp, constrain, scaling, kfold_inner, kfold_outer, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

